### ISSUE TITLE
key :key not found in [store: PhoenixLiveSession, pub_sub, Sage.PubSub, signing_salt.....

### ISSUE THREAD

**Issue by shortly-portly** [pentacent/phoenix_live_session#2]
Hello. 

Just following the instructions to use PhoenixLiveSession and I'm getting the error in the title key :key not found. It is unclear to me whether I should simply add the :key or if it is not required and I've done something wrong :-). 

I'm using

      {:phoenix, "~> 1.5.7"},
      {:phoenix_live_view, "~> 0.15.0"},
      {:phoenix_live_session, "~> 0.1"}

cheers

**Comment by wmnnd** [comment]
Could you share the code you’ve used for configuring Live Sessions and the exact error message?

**Comment by shortly-portly** [comment]
Hi my endpoint.ex is:

 ```
@session_options [
    store: PhoenixLiveSession,
    pub_sub: Sage.PubSub,
    signing_salt: "2Ytbl+mr"
  ]
```

and the error I get is....
```

== Compilation error in file lib/sage_web/endpoint.ex ==
** (KeyError) key :key not found in: [store: PhoenixLiveSession, pub_sub: Sage.PubSub, signing_salt: "2Ytbl+mr"]
    (elixir 1.11.2) lib/keyword.ex:420: Keyword.fetch!/2
    (phoenix 1.5.7) lib/phoenix/socket/transport.ex:270: Phoenix.Socket.Transport.init_session/1
    (phoenix 1.5.7) lib/phoenix/socket/transport.ex:255: anonymous fn/1 in Phoenix.Socket.Transport.load_config/1
    (elixir 1.11.2) lib/enum.ex:1399: Enum."-map/2-lists^map/1-0-"/2
    (phoenix 1.5.7) lib/phoenix/socket/transport.ex:250: Phoenix.Socket.Transport.load_config/1
    (phoenix 1.5.7) lib/phoenix/endpoint.ex:638: Phoenix.Endpoint.socket_paths/4
    (phoenix 1.5.7) lib/phoenix/endpoint.ex:591: anonymous fn/3 in Phoenix.Endpoint."MACRO-__before_compile__"/2
    (elixir 1.11.2) lib/enum.ex:2181: Enum."-reduce/3-lists^foldl/2-0-"/3
    (phoenix 1.5.7) expanding macro: Phoenix.Endpoint.__before_compile__/1
    lib/sage_web/endpoint.ex:1: SageWeb.Endpoint (module)
    (elixir 1.11.2) lib/kernel/parallel_compiler.ex:314: anonymous fn/4 in Kernel.ParallelCompiler.spawn_workers/7
```

**Comment by shortly-portly** [comment]
Adding :key appears to get it to work but I'm worried this is masking an issue. cheers

**Comment by wmnnd** [comment]
Yes, adding `:key` is necessary when defining a session, this should be clearer in the README. I’ll fix it there, thanks for pointing it out!

**Comment by shortly-portly** [comment]
No problem at all - thanks for the awesome library.
